### ISSUE TITLE
arm64

### ISSUE THREAD

**Issue by eriksmets** [BishopFox/theos-jailed#2]
Any chance of making this compatible with arm64 ?

**Comment by 0xhaggis** [comment]
It's already compatible with AArch64, we've used it internally to deploy patches to apps on an iPhone 6. Please file a specific bug (with reproduction steps) if something isn't working for you!

**Comment by lemonhead94** [comment]
Hey guys having the same problem when trying to compile a tweak.
Makefile: ARCHS: arm64

[...]libsubstrate.dylib, file was built for armv7 which is not the architecture being linked (arm64):[...]

**Comment by skram** [comment]
Didn't change anything in Tweak.xm, just went through the rest of the motions to install on a non-jailbroken device and I get this:

Dyld Error Message:
Dyld Message: Library not loaded: @executable_path/unconfirmed.dylib
  Referenced from: /var/mobile/Containers/Bundle/Application/1199120E-C27B-4118-AAFC-61DB7973E706/App.app/App
  Reason: no suitable image found.  Did find:
    /var/mobile/Containers/Bundle/Application/1199120E-C27B-4118-AAFC-61DB7973E706/Adidas.app/unconfirmed.dylib: mach-o, but wrong architecture
    /private/var/mobile/Containers/Bundle/Application/1199120E-C27B-4118-AAFC-61DB7973E706/Adidas.app/unconfirmed.dylib: mach-o, but wrong architecture
  Dyld Version: 369.12

I take it, it's /not/ compatible with arm64 ?

**Comment by WilliamLCobb** [comment]
I just got this same message. Did you fix it?

**Comment by h4gg1s** [comment]
It is compatible with arm64. Can you run "/usr/bin/file unconfirmed.dylib" from within the directory containing unconfirmed.dylib and paste the output?

**Comment by WilliamLCobb** [comment]
$/usr/bin/file /Users/willcobb/Dropbox/Xcode/Cydia/PokemonGoAnywhere/Jailed/pokemongoanywhere/obj/PokemonGoAnywhere.dylib 
/Users/willcobb/Dropbox/Xcode/Cydia/PokemonGoAnywhere/Jailed/pokemongoanywhere/obj/PokemonGoAnywhere.dylib: Mach-O dynamically linked shared library arm

$ lipo -info /Users/willcobb/Dropbox/Xcode/Cydia/PokemonGoAnywhere/Jailed/pokemongoanywhere/obj/PokemonGoAnywhere.dylib 
Non-fat file: /Users/willcobb/Dropbox/Xcode/Cydia/PokemonGoAnywhere/Jailed/pokemongoanywhere/obj/PokemonGoAnywhere.dylib is architecture: armv7

$ /usr/bin/file /Users/willcobb/Dropbox/Xcode/Cydia/PokemonGoAnywhere/Jailed/pokemongoanywhere/theos/lib/libsubstrate.dylib 
/Users/willcobb/Dropbox/Xcode/Cydia/PokemonGoAnywhere/Jailed/pokemongoanywhere/theos/lib/libsubstrate.dylib: Mach-O universal binary with 3 architectures
/Users/willcobb/Dropbox/Xcode/Cydia/PokemonGoAnywhere/Jailed/pokemongoanywhere/theos/lib/libsubstrate.dylib (for architecture armv6):   Mach-O dynamically linked shared library arm
/Users/willcobb/Dropbox/Xcode/Cydia/PokemonGoAnywhere/Jailed/pokemongoanywhere/theos/lib/libsubstrate.dylib (for architecture armv7):   Mach-O dynamically linked shared library arm
/Users/willcobb/Dropbox/Xcode/Cydia/PokemonGoAnywhere/Jailed/pokemongoanywhere/theos/lib/libsubstrate.dylib (for architecture arm64):   Mach-O 64-bit dynamically linked shared library

I replaced libsubstrate with one that includes 64bit, but no luck

**Comment by Dry05** [comment]
Use this version of theos-jailed https://github.com/shuoshi/theos-jailed he combined arm64 in the original libsubstrate from theos-jailed. This one works i can confirm

**Comment by moloch--** [comment]
I'm glad that I'm not the only hacker that has gotten sucked into Pokemon Go...
