### ISSUE TITLE
Failed to inject APPNAME.dylib

### ISSUE THREAD

**Issue by Arizona94** [BishopFox/theos-jailed#5]
When i attempt to patch the .ipa file, I get the error that it failed to inject [appname].dylib and asks if I care debug the problem. I had to install optool and I updated patchapp.sh but I must have messed up somewhere. How can I determine what is causing this issue?

**Comment by urosch** [comment]
I know this was 4 months ago but I have the same problem and would like some info as to what you had to do to fix your issue.
Thank you in advance!
